import type { FormValues } from "@/home/pages/AddWebsite";

export const countryOptions = [
  {
    name: "gb",
    displayName: "United Kingdom",
    flagUrl: "https://flagcdn.com/w40/gb.png"
  },
  {
    name: "fr",
    displayName: "France",
    flagUrl: "https://flagcdn.com/w40/fr.png"
  },
  {
    name: "de",
    displayName: "Germany",
    flagUrl: "https://flagcdn.com/w40/de.png"
  },
  {
    name: "us",
    displayName: "United States",
    flagUrl: "https://flagcdn.com/w40/us.png"
  },
  {
    name: "in",
    displayName: "India",
    flagUrl: "https://flagcdn.com/w40/in.png"
  }
];

export const languageOptions = [
  {
    name: "gb",
    displayName: "English UK",
    flagUrl: "https://flagcdn.com/w40/gb.png"
  },
  {
    name: "fr",
    displayName: "French",
    flagUrl: "https://flagcdn.com/w40/fr.png"
  },
  {
    name: "de",
    displayName: "German",
    flagUrl: "https://flagcdn.com/w40/de.png"
  },
  {
    name: "us",
    displayName: "English US",
    flagUrl: "https://flagcdn.com/w40/us.png"
  },
  {
    name: "in",
    displayName: "Hindi",
    flagUrl: "https://flagcdn.com/w40/in.png"
  }
];

export const categoryOptions = [
  { label: "Animals / Pets", value: "animals_pets" },
  { label: "Art", value: "art" },
  { label: "Auto", value: "auto" },
  { label: "Beauty", value: "beauty" },
  { label: "Blogging", value: "blogging" },
  { label: "Business / Entrepreneur", value: "business_entrepreneur" },
  { label: "Directory", value: "directory" },

  { label: "Education", value: "education" },
  { label: "Energy & Solar Energy", value: "energy_solar" },
  { label: "Entertainment & Music", value: "entertainment_music" },
  { label: "Environment", value: "environment" },
  { label: "Events", value: "events" },
  { label: "Family / Parenting", value: "family_parenting" },
  { label: "Fashion", value: "fashion" },
  { label: "Finance", value: "finance" },

  { label: "Food", value: "food" },
  { label: "Gambling", value: "gambling" },
  { label: "Gaming", value: "gaming" },
  { label: "General", value: "general" },
  { label: "Health & Fitness", value: "health_fitness" },
  { label: "Home & Garden", value: "home_garden" },
  { label: "Italian Sites", value: "italian_sites" },
  { label: "Legal", value: "legal" },

  { label: "Lifestyle", value: "lifestyle" },
  { label: "Marijuana / Vaporizers", value: "marijuana_vaporizers" },
  { label: "Marketing", value: "marketing" },
  { label: "Medical", value: "medical" },
  { label: "News", value: "news" },
  { label: "Other", value: "other" },
  { label: "Outdoors", value: "outdoors" },
  { label: "Photography", value: "photography" },

  { label: "Politics", value: "politics" },
  { label: "Real Estate", value: "real_estate" },
  { label: "EnvironmentSafety", value: "environment_safety" },
  { label: "SEO", value: "seo" },
  { label: "Sex & Adult", value: "sex_adult" },
  { label: "Shopping", value: "shopping" }
];

export const dummyData: FormValues[] = [
  {
    website: "https://example1.com",
    id: "gAMClFCg-jetrlRYIwJbq",
    mainCategory: ["technology"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Tech-focused site",
    offerGuidelines: "Tech only",
    noOfLinksAdvertise: "2",
    noOfWords: "1000",
    homePageLinkPrice: 200,
    linkInsertion: 100,
    guestPosting: 150,
    writingArticleIncluded: "1",
    isSamePrice: "",
    enterSamePrice: "",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "1",
    taggingArticle: "1",
    otherLinks: "1",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://example2.com",
    id: "QQ1fhWM88GvyWBI22TIwB",
    mainCategory: ["education", "science"],
    majorTraffic: "in",
    primaryLang: "in",
    description: "Education content",
    offerGuidelines: "Students only",
    noOfLinksAdvertise: "1",
    noOfWords: "1200",
    homePageLinkPrice: 150,
    linkInsertion: 80,
    guestPosting: 120,
    writingArticleIncluded: "2",
    isSamePrice: "same",
    enterSamePrice: "100",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "2",
    otherLinks: "1",
    otherContent: "Handouts",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://example3.com",
    id: "B4XQUnq4oich31Za4iWwF",
    mainCategory: ["photography", "travel"],
    majorTraffic: "fr",
    primaryLang: "us",
    description: "Travel photos",
    offerGuidelines: "HD only",
    noOfLinksAdvertise: "2",
    noOfWords: "800",
    homePageLinkPrice: 180,
    linkInsertion: 90,
    guestPosting: 100,
    writingArticleIncluded: "1",
    isSamePrice: "same",
    enterSamePrice: "88",
    owner: [],
    allowDoFollow: "",
    typesOfLink: "",
    taggingArticle: "",
    otherLinks: "",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://site4.com",
    id: "r6TxvXnbWzqLqGB9mvfQA",
    mainCategory: ["fashion", "lifestyle"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Fashion trends",
    offerGuidelines: "Images required",
    noOfLinksAdvertise: "1",
    noOfWords: "600",
    homePageLinkPrice: 140,
    linkInsertion: 60,
    guestPosting: 100,
    writingArticleIncluded: "2",
    isSamePrice: "same",
    enterSamePrice: "140",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "2",
    otherLinks: "2",
    otherContent: "Lookbook",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "1000",
    isSamePrice: "",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 110,
    crptoGuestPost: 190,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "",
    homePageLinkPrice: 210,
    linkInsertion: 110,
    guestPosting: 190,
    offerGuidelines: "Crypto only",
    description: "Blockchain updates",
    mainCategory: ["crypto"],
    majorTraffic: "us",
    primaryLang: "fr",
    website: "https://site5.com",
    id: "zEKGpFr48kEr0ZdGzToFz",
    writingArticleIncluded: "1",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "3",
    otherLinks: "0",
    otherContent: "",
    hasConsented: true
  },
  {
    website: "https://site6.com",
    id: "bZr1KZq3A1YeFMvWn1LEg",
    mainCategory: ["gambling"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Casino reviews",
    offerGuidelines: "No affiliate links",
    noOfLinksAdvertise: "2",
    noOfWords: "750",
    homePageLinkPrice: 220,
    linkInsertion: 115,
    guestPosting: 175,
    writingArticleIncluded: "2",
    isSamePrice: "same",
    enterSamePrice: "150",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "1",
    otherLinks: "",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 175,
    gamblingLinkInsert: 115,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://site7.com",
    id: "YnQx9dJvVoT2nDRZT0XHr",
    mainCategory: ["adult", "health"],
    majorTraffic: "fr",
    primaryLang: "fr",
    description: "Adult health and wellness",
    offerGuidelines: "NSFW okay",
    noOfLinksAdvertise: "1",
    noOfWords: "850",
    homePageLinkPrice: 200,
    linkInsertion: 100,
    guestPosting: 180,
    writingArticleIncluded: "1",
    isSamePrice: "",
    enterSamePrice: "",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "3",
    taggingArticle: "2",
    otherLinks: "",
    otherContent: "",
    hasConsented: true,
    adultGuestPost: 180,
    adultLinkInsert: 100,
    crptoGuestPost: 0,
    gamblingGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0
  },
  {
    website: "https://site8.com",
    id: "Nf2hLwKe0nTfCcRzYj8Vu",
    mainCategory: ["seo", "marketing"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "SEO agency site",
    offerGuidelines: "Link in body only",
    noOfLinksAdvertise: "2",
    noOfWords: "900",
    homePageLinkPrice: 180,
    linkInsertion: 90,
    guestPosting: 160,
    writingArticleIncluded: "2",
    isSamePrice: "",
    enterSamePrice: "",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "1",
    otherLinks: "",
    otherContent: "Infographics",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://site9.com",
    id: "HtLsA2eUobMR0YZKpXFiJ",
    mainCategory: ["medical", "research"],
    majorTraffic: "in",
    primaryLang: "in",
    description: "Medical research blog",
    offerGuidelines: "Verified data only",
    noOfLinksAdvertise: "1",
    noOfWords: "1100",
    homePageLinkPrice: 160,
    linkInsertion: 75,
    guestPosting: 140,
    writingArticleIncluded: "1",
    isSamePrice: "same",
    enterSamePrice: "140",
    owner: [],
    allowDoFollow: "1",
    typesOfLink: "1",
    taggingArticle: "1",
    otherLinks: "1",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://site10.com",
    id: "xQ3LpEzNf4Us9BKcYzMj7",
    mainCategory: ["fashion"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Trendy fashion posts",
    offerGuidelines: "Seasonal updates",
    noOfLinksAdvertise: "2",
    noOfWords: "1000",
    homePageLinkPrice: 190,
    linkInsertion: 95,
    guestPosting: 150,
    writingArticleIncluded: "1",
    isSamePrice: "same",
    enterSamePrice: "160",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "2",
    otherLinks: "2",
    otherContent: "Style guide",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    website: "https://site11.com",
    id: "aDzN3rGjYEqp9MfVTlWx8",
    mainCategory: ["environment", "green_energy"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Eco-friendly content",
    offerGuidelines: "No fossil fuel links",
    noOfLinksAdvertise: "1",
    noOfWords: "850",
    homePageLinkPrice: 140,
    linkInsertion: 60,
    guestPosting: 110,
    writingArticleIncluded: "2",
    isSamePrice: "",
    enterSamePrice: "",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "1",
    otherLinks: "",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    noOfLinksAdvertise: "2",
    linksMax: 200,
    linksMin: 100,
    noOfWords: "1000",
    isSamePrice: "same",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 90,
    gamblingGuestPost: 160,
    enterSamePrice: "130",
    homePageLinkPrice: 160,
    linkInsertion: 90,
    guestPosting: 130,
    offerGuidelines: "Only football links",
    description: "Football fan blog",
    mainCategory: ["sports", "home_garden"],
    majorTraffic: "in",
    primaryLang: "in",
    website: "https://site12.com",
    id: "jUwZfPbR6LoMc3xYtVkEp",
    writingArticleIncluded: "1",
    owner: [],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "3",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "2",
    linksMax: 200,
    linksMin: 100,
    noOfWords: "900",
    isSamePrice: "",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "",
    homePageLinkPrice: 170,
    linkInsertion: 85,
    guestPosting: 145,
    offerGuidelines: "No junk food",
    description: "Healthy food and lifestyle",
    mainCategory: ["lifestyle", "food"],
    majorTraffic: "de",
    primaryLang: "fr",
    website: "https://site13.com",
    id: "ZvGpYcMiXoH8TNuV3KrWy",
    writingArticleIncluded: "1",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "2",
    taggingArticle: "2",
    otherLinks: "1",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "750",
    isSamePrice: "same",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "120",
    homePageLinkPrice: 130,
    linkInsertion: 70,
    guestPosting: 120,
    offerGuidelines: "Animal friendly only",
    description: "Dog care tips",
    mainCategory: ["pets"],
    majorTraffic: "in",
    primaryLang: "us",
    website: "https://site14.com",
    id: "wLznEoqbMTks3Gy9hDJ7C",
    writingArticleIncluded: "1",
    owner: [],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "2",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    website: "https://site15.com",
    id: "kEhV6QvYZrDbt1JNF2pRo",
    mainCategory: ["real_estate"],
    majorTraffic: "us",
    primaryLang: "us",
    description: "Property listings",
    offerGuidelines: "No spammy links",
    noOfLinksAdvertise: "1",
    noOfWords: "950",
    homePageLinkPrice: 200,
    linkInsertion: 110,
    guestPosting: 160,
    writingArticleIncluded: "2",
    isSamePrice: "",
    enterSamePrice: "",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "1",
    taggingArticle: "2",
    otherLinks: "",
    otherContent: "",
    hasConsented: true,
    gamblingGuestPost: 0,
    crptoGuestPost: 0,
    adultGuestPost: 0,
    gamblingLinkInsert: 0,
    crptoLinkInsert: 0,
    adultLinkInsert: 0
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "1000",
    isSamePrice: "same",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "170",
    homePageLinkPrice: 190,
    linkInsertion: 100,
    guestPosting: 170,
    offerGuidelines: "Fact-checked only",
    description: "Independent news",
    mainCategory: ["news", "politics"],
    majorTraffic: "us",
    primaryLang: "us",
    website: "https://site16.com",
    id: "XwDYCrj9bqRoZNgJi8Lma",
    writingArticleIncluded: "2",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "3",
    taggingArticle: "3",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "2",
    linksMax: 200,
    linksMin: 0,
    noOfWords: "1050",
    isSamePrice: "",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 100,
    crptoGuestPost: 150,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "",
    homePageLinkPrice: 200,
    linkInsertion: 100,
    guestPosting: 150,
    offerGuidelines: "No risk advice",
    description: "Investment tips",
    mainCategory: ["finance", "investing"],
    majorTraffic: "de",
    primaryLang: "de",
    website: "https://site17.com",
    id: "VeHjfzYRXtUjLnMKwE0pB",
    writingArticleIncluded: "1",
    owner: [],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "2",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "1000",
    isSamePrice: "same",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "140",
    homePageLinkPrice: 190,
    linkInsertion: 100,
    guestPosting: 140,
    offerGuidelines: "No AI-generated",
    description: "Tech tutorials",
    mainCategory: ["programming", "tech"],
    majorTraffic: "us",
    primaryLang: "us",
    website: "https://site18.com",
    id: "FmXWbAhNzRcG1PKXYyAso",
    writingArticleIncluded: "2",
    owner: ["isOwner"],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "2",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "800",
    isSamePrice: "",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "",
    homePageLinkPrice: 140,
    linkInsertion: 60,
    guestPosting: 90,
    offerGuidelines: "No spoilers",
    description: "Book reviews",
    mainCategory: ["books", "reviews"],
    majorTraffic: "in",
    primaryLang: "de",
    website: "https://site19.com",
    id: "LrJhSyw3Kp9hXnEJ6Mzvd",
    writingArticleIncluded: "1",
    owner: [],
    allowDoFollow: "2",
    typesOfLink: "1",
    taggingArticle: "1",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  },
  {
    noOfLinksAdvertise: "1",
    noOfWords: "950",
    isSamePrice: "same",
    adultLinkInsert: 0,
    adultGuestPost: 0,
    crptoLinkInsert: 0,
    crptoGuestPost: 0,
    gamblingLinkInsert: 0,
    gamblingGuestPost: 0,
    enterSamePrice: "120",
    homePageLinkPrice: 160,
    linkInsertion: 85,
    guestPosting: 120,
    offerGuidelines: "No blurry images",
    description: "DSLR tips and tricks",
    mainCategory: ["photography"],
    majorTraffic: "gb",
    primaryLang: "gb",
    website: "https://site20.com",
    id: "Yt9MchFd1RoPzVKjGvNxd",
    writingArticleIncluded: "2",
    owner: ["isOwner"],
    allowDoFollow: "1",
    typesOfLink: "2",
    taggingArticle: "3",
    otherLinks: "",
    otherContent: "",
    hasConsented: true
  }
];
